[build]
  # Ensure this path matches where your build output is located
  publish = "client/build"
  command = "cd client && npm install && npm run build"

[[redirects]]
  from = "/success"
  to = "/index.html"
  status = 200
